Repository boostcampwm-2022/web37-ZelloDraw, pull requests merged in 2022-11, with the labels that each got.

#5 [feature] create-lobby 핸들러 구현
  backend/package-lock.json
  backend/package.json
  backend/src/app.controller.spec.ts
  backend/src/app.controller.ts
  backend/src/app.module.ts
  backend/src/app.service.ts
  backend/src/core/core.gateway.spec.ts
  backend/src/core/core.gateway.ts
  backend/src/core/core.module.ts
  backend/src/core/lobby.service.ts
  backend/src/main.ts
  backend/test/app.e2e-spec.ts
Labels: feat, BE

#6 [feature] join-lobby 핸들러 구현
  backend/src/core/core.gateway.ts
  backend/src/core/lobby.service.ts
Labels: 백엔드, BE

#7 [feature] start-game 핸들러 구현
  backend/src/core/core.gateway.ts
  backend/src/core/lobby.service.ts
Labels: 백엔드, BE

#9 [feat] Game page 퍼블리싱
  frontend/src/App.tsx
  frontend/src/assets/background.svg
  frontend/src/assets/logo-s.svg
  frontend/src/assets/sketchbook.svg
  frontend/src/components/CameraButton.tsx
  frontend/src/components/Card.tsx
  frontend/src/components/DrawingTools.tsx
  frontend/src/components/GameUsers.tsx
  frontend/src/components/SketchbookCard.tsx
  frontend/src/components/Timer.tsx
  frontend/src/components/VideoCallUser.tsx
  frontend/src/pages/Game.tsx
  frontend/src/styles/GlobalStyle.ts
  frontend/src/styles/ZelloTheme.ts
  frontend/src/styles/styled.ts
Labels: feat, FE

#8 [feat] leave-lobby 핸들러 구현
  backend/src/core/core.gateway.ts
  backend/src/core/lobby.service.ts
Labels: feat, refactor, BE

#11 [fix] leave-lobby 핸들러 관련 코드 수정
  backend/src/core/core.gateway.ts
  backend/src/core/lobby.service.ts
Labels: refactor, BE

#14 [feat] 로비 벗어나기 기능, 유저 이름 변경 기능 구현
  backend/src/core/core.gateway.ts
  backend/src/core/lobby.service.ts
  backend/src/core/user.dto.ts
  backend/src/core/user.model.ts
  backend/src/core/user.service.ts
  frontend/src/atoms/user.ts
  frontend/src/components/InfoCard.tsx
  frontend/src/components/UserCard.tsx
  frontend/src/pages/Lobby.tsx
  frontend/src/pages/Main.tsx
Labels: feat, FE, BE

#16 [fix] 메인, 로비페이지 코드리뷰 반영 수정
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/logo-l.png
  frontend/src/assets/logo-l.svg
  frontend/src/assets/logo-s.png
  frontend/src/assets/logo-s.svg
  frontend/src/components/GameModeList.tsx
  frontend/src/components/InfoCard.tsx
  frontend/src/components/InfoCarousel.tsx
  frontend/src/components/InviteButton.tsx
  frontend/src/components/ToastMessage.tsx
  frontend/src/components/UserCard.tsx
  frontend/src/pages/Game.tsx
  frontend/src/pages/Lobby.tsx
  frontend/src/pages/Main.tsx
Labels: FE

#21 [feat] 소켓 통신 예외 처리 구현 + 존재하지 않는 lobby에 진입 시 처리
  backend/src/core/core.gateway.ts
  backend/src/core/socket.exception.ts
  backend/src/core/socket.filter.ts
  frontend/src/pages/Lobby.tsx
  frontend/src/services/socketService.ts
Labels: feat, FE, BE

#23 [feat] start-round 관련 코드 리팩터링
  frontend/src/components/GameModeList.tsx
  frontend/src/components/GameStartButton.tsx
  frontend/src/game/NetworkServiceUtils.ts
  frontend/src/pages/Game.tsx
Labels: FE

#27 [refactor] Backend 클래스 다이어그램 설계 및 코드 변경
  backend/src/core/core.gateway.ts
  backend/src/core/core.module.ts
  backend/src/core/game.dto.ts
  backend/src/core/game.interface.ts
  backend/src/core/game.service.ts
  backend/src/core/gameLobby.model.ts
  backend/src/core/gamelobby.repository.ts
  backend/src/core/lobby.interface.ts
  backend/src/core/lobby.service.ts
  backend/src/core/quizReply.model.ts
  backend/src/core/quizReplyChain.model.ts
Labels: refactor, BE

#30 [feat] 로비에 8명 이상 접속, 모든 유저가 로비에서 나갔을 때 로직 추가
  backend/src/core/gamelobby.repository.ts
  backend/src/core/lobby.service.ts
Labels: feat, BE

#35 hotfix/react-build-error
  frontend/package-lock.json
  frontend/package.json
Labels: FE, fix
